export function isAuthenticated() {
    if (localStorage.getItem("Bearer")) {
        return true;

    }
    return false;


}

export function getToken() {
    return localStorage.getItem("Bearer")

}

export function isAdmin() {
    if (isAuthenticated()) {
        const roles = localStorage.getItem("Role");
        return roles.includes("ADMIN");
    }
    return false;


}

export function handleLogOut() {
    localStorage.removeItem("Bearer")
    localStorage.removeItem("Role")


}

export function currencyOptions() {
    return [{value: "USD", id: 1},
        {value: "AED", id: 2},
        {value: "AFN", id: 3},
        {value: "ALL", id: 4},
        {value: "AMD", id: 5},
        {value: "ANG", id: 6},
        {value: "AOA", id: 7},
        {value: "ARS", id: 8},
        {value: "AUD", id: 9},
        {value: "AWG", id: 10},
        {value: "AZN", id: 11},
        {value: "BAM", id: 12},
        {value: "BBD", id: 13},
        {value: "BDT", id: 14},
        {value: "BGN", id: 15},
        {value: "BHD", id: 16},
        {value: "BIF", id: 17},
        {value: "BMD", id: 18},
        {value: "BND", id: 19},
        {value: "BOB", id: 20},
        {value: "BRL", id: 21},
        {value: "BSD", id: 22},
        {value: "BTN", id: 23},
        {value: "BWP", id: 24},
        {value: "BYN", id: 25},
        {value: "BZD", id: 26},
        {value: "CAD", id: 27},
        {value: "CDF", id: 28},
        {value: "CHF", id: 29},
        {value: "CLP", id: 30},
        {value: "CNY", id: 31},
        {value: "COP", id: 32},
        {value: "CRC", id: 33},
        {value: "CUP", id: 34},
        {value: "CVE", id: 35},
        {value: "CZK", id: 36},
        {value: "DJF", id: 37},
        {value: "DKK", id: 38},
        {value: "DOP", id: 39},
        {value: "DZD", id: 40},
        {value: "EGP", id: 41},
        {value: "ERN", id: 42},
        {value: "ETB", id: 43},
        {value: "EUR", id: 44},
        {value: "FJD", id: 45},
        {value: "FKP", id: 46},
        {value: "FOK", id: 47},
        {value: "GBP", id: 48},
        {value: "GEL", id: 49},
        {value: "GGP", id: 50},
        {value: "GHS", id: 51},
        {value: "GIP", id: 52},
        {value: "GMD", id: 53},
        {value: "GNF", id: 54},
        {value: "GTQ", id: 55},
        {value: "GYD", id: 56},
        {value: "HKD", id: 57},
        {value: "HNL", id: 58},
        {value: "HRK", id: 59},
        {value: "HTG", id: 60},
        {value: "HUF", id: 61},
        {value: "IDR", id: 62},
        {value: "ILS", id: 63},
        {value: "IMP", id: 64},
        {value: "INR", id: 65},
        {value: "IQD", id: 66},
        {value: "IRR", id: 67},
        {value: "ISK", id: 68},
        {value: "JEP", id: 69},
        {value: "JMD", id: 70},
        {value: "JOD", id: 71},
        {value: "JPY", id: 72},
        {value: "KES", id: 73},
        {value: "KGS", id: 74},
        {value: "KHR", id: 75},
        {value: "KID", id: 76},
        {value: "KMF", id: 77},
        {value: "KRW", id: 78},
        {value: "KWD", id: 79},
        {value: "KYD", id: 80},
        {value: "KZT", id: 81},
        {value: "LAK", id: 82},
        {value: "LBP", id: 83},
        {value: "LKR", id: 84},
        {value: "LRD", id: 85},
        {value: "LSL", id: 86},
        {value: "LYD", id: 87},
        {value: "MAD", id: 88},
        {value: "MDL", id: 89},
        {value: "MGA", id: 90},
        {value: "MKD", id: 91},
        {value: "MMK", id: 92},
        {value: "MNT", id: 93},
        {value: "MOP", id: 94},
        {value: "MRU", id: 95},
        {value: "MUR", id: 96},
        {value: "MVR", id: 97},
        {value: "MWK", id: 98},
        {value: "MXN", id: 99},
        {value: "MYR", id: 100},
        {value: "MZN", id: 101},
        {value: "NAD", id: 102},
        {value: "NGN", id: 103},
        {value: "NIO", id: 104},
        {value: "NOK", id: 105},
        {value: "NPR", id: 106},
        {value: "NZD", id: 107},
        {value: "OMR", id: 108},
        {value: "PAB", id: 109},
        {value: "PEN", id: 110},
        {value: "PGK", id: 111},
        {value: "PHP", id: 112},
        {value: "PKR", id: 113},
        {value: "PLN", id: 114},
        {value: "PYG", id: 115},
        {value: "QAR", id: 116},
        {value: "RON", id: 117},
        {value: "RSD", id: 118},
        {value: "RUB", id: 119},
        {value: "RWF", id: 120},
        {value: "SAR", id: 130},
        {value: "SBD", id: 131},
        {value: "SCR", id: 132},
        {value: "SDG", id: 133},
        {value: "SEK", id: 134},
        {value: "SGD", id: 135},
        {value: "SHP", id: 136},
        {value: "SLE", id: 137},
        {value: "SLL", id: 138},
        {value: "SOS", id: 139},
        {value: "SRD", id: 140},
        {value: "SSP", id: 141},
        {value: "STN", id: 142},
        {value: "SYP", id: 143},
        {value: "SZL", id: 144},
        {value: "THB", id: 145},
        {value: "TJS", id: 146},
        {value: "TMT", id: 147},
        {value: "TND", id: 148},
        {value: "TOP", id: 149},
        {value: "TRY", id: 150},
        {value: "TTD", id: 151},
        {value: "TVD", id: 152},
        {value: "TWD", id: 153},
        {value: "TZS", id: 154},
        {value: "UAH", id: 155},
        {value: "UGX", id: 156},
        {value: "UYU", id: 157},
        {value: "UZS", id: 158},
        {value: "VES", id: 159},
        {value: "VND", id: 160},
        {value: "VUV", id: 161},
        {value: "WST", id: 162},
        {value: "XAF", id: 163},
        {value: "XCD", id: 164},
        {value: "XDR", id: 165},
        {value: "XOF", id: 166},
        {value: "XPF", id: 167},
        {value: "YER", id: 168},
        {value: "ZAR", id: 169},
        {value: "ZMW", id: 170},
        {value: "ZWL", id: 171}];
}

